//! Application-layer duplex on the L0 exclusive occupancy pipe.
//!
//! SI implements **`l0_listen` / `l0_connect`** (or `mining` + `listenKind: "l0"`):
//! idle L0 SSE may still receive user-PGP gossip; the first `l0_connect` occupies
//! the SSE, SI pipes remaining TCP, then rejects later inflows (409).
//! Application JSON `duplex_offer` / `duplex_accept` / `duplex_reject` /
//! `duplex_frame` is **not** an SI command. Offer stays user-PGP Chat gossip
//! so it cannot occupy the exclusive L0 listen. Accept / reject / frames are
//! AES-256-GCM blobs on the occupied pipe. Missing accept keeps P1 gossip.
//! Do not send `listenKind: "duplex"` or SI `duplex_*`.

use crate::error::L0dError;
use crate::l0::aes;
use crate::l0::eip191::EthSecret;
use crate::l0::pgp;
use base64::Engine;
use serde_json::Value;
use tiny_keccak::{Hasher, Keccak};

pub fn normalize_eoa(raw: &str) -> Result<String, L0dError> {
    let t = raw.trim();
    if t.len() != 42 || !t.starts_with("0x") && !t.starts_with("0X") {
        let lower = t.to_ascii_lowercase();
        if lower.len() == 40 && lower.chars().all(|c| c.is_ascii_hexdigit()) {
            return Ok(format!("0x{lower}"));
        }
        return Err(L0dError::L0("duplex wallet must be 0x + 40 hex".into()));
    }
    let hex = &t[2..];
    if hex.len() != 40 || !hex.chars().all(|c| c.is_ascii_hexdigit()) {
        return Err(L0dError::L0("duplex wallet must be 0x + 40 hex".into()));
    }
    Ok(format!("0x{}", hex.to_ascii_lowercase()))
}

/// Create a fresh opaque handle for one logical pipe incarnation.
///
/// The handle is generated by an endpoint, carried only inside the
/// endpoint-to-endpoint encrypted handshake, and is never derived from wallet
/// addresses or ports. SI must treat it as an opaque local correlation value.
pub fn new_pipe_handle() -> String {
    let key = aes::generate_key();
    let mut hasher = Keccak::v256();
    hasher.update(b"l0d-pipe-handle-v2|");
    hasher.update(&key);
    let mut out = [0u8; 32];
    hasher.finalize(&mut out);
    hex::encode(out)
}

pub fn we_are_initiator(own_eoa: &str, peer_eoa: &str) -> Result<bool, L0dError> {
    Ok(normalize_eoa(own_eoa)? < normalize_eoa(peer_eoa)?)
}

pub fn encode_offer_command(
    initiator_wallet: &str,
    peer_wallet: &str,
    listen_wallet: &str,
    listen_user_pgp: &str,
    session_id: &str,
    key: &[u8; aes::KEY_LEN],
    timestamp: u64,
) -> Result<String, L0dError> {
    encode_offer_command_for_port(
        initiator_wallet,
        peer_wallet,
        peer_wallet,
        listen_wallet,
        listen_user_pgp,
        0,
        session_id,
        key,
        timestamp,
    )
}

/// Build an offer addressed by the server's main wallet and logical port.
/// The server allocates a fresh temporary identity after accepting it.
pub fn encode_offer_command_for_port(
    initiator_wallet: &str,
    main_wallet: &str,
    peer_wallet: &str,
    listen_wallet: &str,
    listen_user_pgp: &str,
    port: u16,
    session_id: &str,
    key: &[u8; aes::KEY_LEN],
    timestamp: u64,
) -> Result<String, L0dError> {
    let json = serde_json::json!({
        "command": "duplex_offer",
        "walletAddress": normalize_eoa(initiator_wallet)?,
        "mainWallet": normalize_eoa(main_wallet)?,
        "peerWallet": normalize_eoa(peer_wallet)?,
        "listenWallet": normalize_eoa(listen_wallet)?,
        "listenUserPgp": listen_user_pgp,
        "port": port,
        "pipe_handle": session_id,
        "algorithm": "aes-256-gcm",
        "Securitykey": aes::key_to_standard_b64(key),
        "timestamp": timestamp,
    });
    serde_json::to_string(&json).map_err(|e| L0dError::L0(e.to_string()))
}

pub fn encode_accept_command(
    responder_wallet: &str,
    listen_wallet: &str,
    listen_user_pgp: &str,
    session_id: &str,
    key: &[u8; aes::KEY_LEN],
    timestamp: u64,
) -> Result<String, L0dError> {
    let json = serde_json::json!({
        "command": "duplex_accept",
        "walletAddress": normalize_eoa(responder_wallet)?,
        "listenWallet": normalize_eoa(listen_wallet)?,
        "listenUserPgp": listen_user_pgp,
        "pipe_handle": session_id,
        "algorithm": "aes-256-gcm",
        "Securitykey": aes::key_to_standard_b64(key),
        "timestamp": timestamp,
    });
    serde_json::to_string(&json).map_err(|e| L0dError::L0(e.to_string()))
}

pub fn encode_reject_command(
    responder_wallet: &str,
    session_id: &str,
    timestamp: u64,
) -> Result<String, L0dError> {
    let json = serde_json::json!({
        "command": "duplex_reject",
        "walletAddress": normalize_eoa(responder_wallet)?,
        "pipe_handle": session_id,
        "reason": "unsupported",
        "timestamp": timestamp,
    });
    let text = serde_json::to_string(&json).map_err(|e| L0dError::L0(e.to_string()))?;
    if text.contains("Securitykey") {
        return Err(L0dError::L0(
            "duplex_reject must not carry Securitykey".into(),
        ));
    }
    Ok(text)
}

pub fn encode_frame_json(session_id: &str, payload_b64: &str) -> Result<String, L0dError> {
    let json = serde_json::json!({
        "type": "duplex_frame",
        "pipe_handle": session_id,
        "payload": payload_b64,
    });
    let text = serde_json::to_string(&json).map_err(|e| L0dError::L0(e.to_string()))?;
    if text.contains("Securitykey") {
        return Err(L0dError::L0(
            "duplex_frame must not carry Securitykey".into(),
        ));
    }
    Ok(text)
}

/// AES-GCM wire blob of `duplex_frame` JSON for the occupied L0 SSE.
/// Inner JSON: `{ "type":"duplex_frame","pipe_handle","payload" }` where `payload`
/// is standard base64 of the `L0D1||IPv4` buffer (JSON cannot carry raw bytes).
/// Outer wire: standard base64 of `nonce(12) || ciphertext || tag(16)`. No OpenPGP.
pub fn seal_frame(
    key: &[u8; aes::KEY_LEN],
    session_id: &str,
    framed: &[u8],
) -> Result<String, L0dError> {
    let payload = Engine::encode(&base64::engine::general_purpose::STANDARD, framed);
    let json = encode_frame_json(session_id, &payload)?;
    aes::seal(key, json.as_bytes())
}

/// AES-GCM keep-alive blob sent by the pipe initiator when there is no IPv4
/// traffic. It keeps the occupied SSE alive without fabricating an IP packet.
pub fn seal_ping(
    key: &[u8; aes::KEY_LEN],
    pipe_handle: &str,
    timestamp: u64,
) -> Result<String, L0dError> {
    let json = serde_json::json!({
        "type": "duplex_ping",
        "pipe_handle": pipe_handle,
        "timestamp": timestamp,
    });
    let text = serde_json::to_string(&json).map_err(|e| L0dError::L0(e.to_string()))?;
    aes::seal(key, text.as_bytes())
}

pub fn looks_like_aes_blob(raw: &str) -> bool {
    let t = raw.trim();
    t.len() >= 32
        && !t.starts_with('{')
        && !t.starts_with("-----")
        && t.bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'+' || b == b'/' || b == b'=')
}

pub fn parse_l0_occupied(payload: &str) -> bool {
    let v: Value = match serde_json::from_str(payload.trim()) {
        Ok(v) => v,
        Err(_) => return false,
    };
    v.get("type").and_then(Value::as_str) == Some("l0_occupied")
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct L0PipeEndInfo {
    pub reason: String,
    pub pipe_handle: String,
}

/// SI teardown notice on the occupied `l0_connect` TCP (one JSON line + `\n`).
pub fn parse_l0_pipe_end(payload: &str) -> Option<L0PipeEndInfo> {
    let v: Value = serde_json::from_str(payload.trim()).ok()?;
    if v.get("type").and_then(Value::as_str) != Some("l0_pipe_end") {
        return None;
    }
    let reason = v
        .get("reason")
        .and_then(Value::as_str)
        .unwrap_or("pipe_end")
        .to_string();
    let pipe_handle = v.get("pipe_handle").and_then(Value::as_str)?;
    if !is_valid_session_id(pipe_handle) {
        return None;
    }
    Some(L0PipeEndInfo {
        reason,
        pipe_handle: pipe_handle.to_string(),
    })
}

/// Pipe handles are lower-case, 32-byte hex values.
fn is_valid_session_id(raw: &str) -> bool {
    raw.len() == 64 && raw.bytes().all(|b| b.is_ascii_hexdigit())
}

/// Sign application JSON and encrypt to the peer **user PGP** only (Chat gossip).
pub fn wrap_app_for_user_pgp(
    command_json: &str,
    user_pub_armored: &str,
    eth: &EthSecret,
) -> Result<String, L0dError> {
    let mut parsed: Value = serde_json::from_str(command_json)
        .map_err(|e| L0dError::L0(format!("duplex app JSON: {e}")))?;
    let wallet = parsed
        .get("walletAddress")
        .and_then(Value::as_str)
        .ok_or_else(|| L0dError::L0("duplex app JSON needs walletAddress".into()))?
        .to_owned();
    if !crate::l0::eip191::eoa_eq(&wallet, eth.address()) && parsed.get("billingWallet").is_none() {
        parsed["billingWallet"] = Value::String(eth.address().to_string());
    }
    let billing_wallet = parsed
        .get("billingWallet")
        .and_then(Value::as_str)
        .unwrap_or(&wallet);
    if !crate::l0::eip191::eoa_eq(billing_wallet, eth.address()) {
        return Err(L0dError::L0(
            "billing ETH key does not match billingWallet".into(),
        ));
    }
    let signed_command = serde_json::to_string(&parsed)
        .map_err(|e| L0dError::L0(format!("duplex app JSON: {e}")))?;
    let sign_message = eth.personal_sign(signed_command.as_bytes())?;
    let envelope = serde_json::json!({
        "message": signed_command,
        "signMessage": sign_message,
    });
    let text = serde_json::to_string(&envelope).map_err(|e| L0dError::L0(e.to_string()))?;
    let b64 = Engine::encode(&base64::engine::general_purpose::STANDARD, text.as_bytes());
    pgp::encrypt_utf8(&b64, user_pub_armored)
}

pub fn wrap_offer_for_user_pgp(
    command_json: &str,
    user_pub_armored: &str,
    eth: &EthSecret,
) -> Result<String, L0dError> {
    if !command_json.contains("\"duplex_offer\"") {
        return Err(L0dError::L0(
            "wrap_offer_for_user_pgp is only for duplex_offer".into(),
        ));
    }
    wrap_app_for_user_pgp(command_json, user_pub_armored, eth)
}

/// Chat-path delivery of `duplex_accept` (control plane). The occupied L0 pipe
/// still carries the same accept as the first AES blob when possible; Chat is
/// the reliable return-path trigger when SSE occupancy data is not ingested.
pub fn wrap_accept_for_user_pgp(
    command_json: &str,
    user_pub_armored: &str,
    eth: &EthSecret,
) -> Result<String, L0dError> {
    if !command_json.contains("\"duplex_accept\"") {
        return Err(L0dError::L0(
            "wrap_accept_for_user_pgp is only for duplex_accept".into(),
        ));
    }
    wrap_app_for_user_pgp(command_json, user_pub_armored, eth)
}

pub fn parse_offer_plain(plain: &str) -> Result<DuplexOffer, L0dError> {
    let v: Value = serde_json::from_str(plain.trim())
        .map_err(|e| L0dError::L0(format!("duplex_offer plaintext: {e}")))?;
    if v.get("command").and_then(Value::as_str) != Some("duplex_offer") {
        return Err(L0dError::L0("not a duplex_offer".into()));
    }
    let session_id = v
        .get("pipe_handle")
        .and_then(Value::as_str)
        .ok_or_else(|| L0dError::L0("duplex_offer missing pipe_handle".into()))?
        .to_string();
    let key = aes::key_from_standard_b64(
        v.get("Securitykey")
            .and_then(Value::as_str)
            .ok_or_else(|| L0dError::L0("duplex_offer missing Securitykey".into()))?,
    )?;
    let listen_wallet = normalize_eoa(
        v.get("listenWallet")
            .and_then(Value::as_str)
            .or_else(|| v.get("walletAddress").and_then(Value::as_str))
            .ok_or_else(|| L0dError::L0("duplex_offer missing listenWallet".into()))?,
    )?;
    let from = normalize_eoa(
        v.get("walletAddress")
            .and_then(Value::as_str)
            .ok_or_else(|| L0dError::L0("duplex_offer missing walletAddress".into()))?,
    )?;
    let main_wallet = normalize_eoa(
        v.get("mainWallet")
            .and_then(Value::as_str)
            .or_else(|| v.get("walletAddress").and_then(Value::as_str))
            .ok_or_else(|| L0dError::L0("duplex_offer missing mainWallet".into()))?,
    )?;
    let port = u16::try_from(
        v.get("port")
            .and_then(Value::as_u64)
            .ok_or_else(|| L0dError::L0("duplex_offer missing port".into()))?,
    )
    .map_err(|_| L0dError::L0("duplex_offer port out of range".into()))?;
    let listen_user_pgp = v
        .get("listenUserPgp")
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_string();
    let timestamp = v
        .get("timestamp")
        .and_then(Value::as_u64)
        .ok_or_else(|| L0dError::L0("duplex_offer missing timestamp".into()))?;
    Ok(DuplexOffer {
        session_id,
        main_wallet,
        port,
        key,
        listen_wallet,
        listen_user_pgp,
        from,
        timestamp,
    })
}

/// Gossip inbound: raw offer JSON, signed `{ message, signMessage }`, or base64 of that wrapper.
pub fn parse_offer_from_inbound_plain(plain: &str) -> Result<DuplexOffer, L0dError> {
    parse_signed_or_raw(plain, |inner| parse_offer_plain(inner))
}

fn parse_signed_or_raw<T>(
    plain: &str,
    parse_inner: impl Fn(&str) -> Result<T, L0dError>,
) -> Result<T, L0dError> {
    let trimmed = plain.trim();
    if trimmed.starts_with('{') {
        if let Ok(v) = serde_json::from_str::<Value>(trimmed) {
            if let Some(msg) = v.get("message").and_then(Value::as_str) {
                if let Ok(got) = parse_inner(msg) {
                    return Ok(got);
                }
            }
            if let Ok(got) = parse_inner(trimmed) {
                return Ok(got);
            }
        }
    }
    if let Ok(raw) = base64::engine::general_purpose::STANDARD.decode(trimmed) {
        if let Ok(inner) = String::from_utf8(raw) {
            let inner_trim = inner.trim();
            if inner_trim.starts_with('{') {
                return parse_signed_or_raw(inner_trim, parse_inner);
            }
        }
    }
    Err(L0dError::L0(
        "inbound plaintext is not duplex app JSON".into(),
    ))
}

#[derive(Clone)]
pub struct DuplexOffer {
    pub session_id: String,
    pub main_wallet: String,
    pub port: u16,
    pub key: [u8; aes::KEY_LEN],
    pub listen_wallet: String,
    pub listen_user_pgp: String,
    pub from: String,
    pub timestamp: u64,
}

#[derive(Clone)]
pub struct DuplexAccept {
    pub session_id: String,
    pub listen_wallet: String,
    pub listen_user_pgp: String,
    pub key: [u8; aes::KEY_LEN],
}

pub fn parse_duplex_frame_json(payload: &str) -> Option<(String, String)> {
    let v: Value = serde_json::from_str(payload.trim()).ok()?;
    if v.get("type").and_then(Value::as_str) != Some("duplex_frame") {
        return None;
    }
    let session_id = v.get("pipe_handle")?.as_str()?.to_string();
    let b64 = v.get("payload")?.as_str()?.to_string();
    Some((session_id, b64))
}

pub fn parse_duplex_ping_json(payload: &str) -> Option<String> {
    let v: Value = serde_json::from_str(payload.trim()).ok()?;
    if v.get("type").and_then(Value::as_str) != Some("duplex_ping") {
        return None;
    }
    v.get("pipe_handle")?.as_str().map(str::to_string)
}

/// App-layer accept on the initiator's session listen SSE (not an SI event).
pub fn parse_accept(payload: &str) -> Option<DuplexAccept> {
    parse_signed_or_raw(payload, |inner| {
        let v: Value = serde_json::from_str(inner.trim())
            .map_err(|e| L0dError::L0(format!("duplex_accept: {e}")))?;
        if v.get("command").and_then(Value::as_str) != Some("duplex_accept") {
            return Err(L0dError::L0("not duplex_accept".into()));
        }
        let session_id = v
            .get("pipe_handle")
            .and_then(Value::as_str)
            .ok_or_else(|| L0dError::L0("duplex_accept missing pipe_handle".into()))?
            .to_string();
        let listen_wallet = normalize_eoa(
            v.get("listenWallet")
                .and_then(Value::as_str)
                .or_else(|| v.get("walletAddress").and_then(Value::as_str))
                .ok_or_else(|| L0dError::L0("duplex_accept missing listenWallet".into()))?,
        )?;
        let key = aes::key_from_standard_b64(
            v.get("Securitykey")
                .and_then(Value::as_str)
                .ok_or_else(|| L0dError::L0("duplex_accept missing Securitykey".into()))?,
        )?;
        let listen_user_pgp = v
            .get("listenUserPgp")
            .and_then(Value::as_str)
            .unwrap_or("")
            .to_string();
        Ok(DuplexAccept {
            session_id,
            listen_wallet,
            listen_user_pgp,
            key,
        })
    })
    .ok()
}

pub fn parse_reject(payload: &str) -> Option<String> {
    parse_signed_or_raw(payload, |inner| {
        let v: Value = serde_json::from_str(inner.trim())
            .map_err(|e| L0dError::L0(format!("duplex_reject: {e}")))?;
        if v.get("command").and_then(Value::as_str) != Some("duplex_reject") {
            return Err(L0dError::L0("not duplex_reject".into()));
        }
        v.get("pipe_handle")
            .and_then(Value::as_str)
            .map(str::to_string)
            .ok_or_else(|| L0dError::L0("duplex_reject missing pipe_handle".into()))
    })
    .ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::l0::eip191::EthSecret;
    use crate::l0::pgp::{decrypt_utf8, generate_test_cert, public_cert_armored};

    fn test_eth() -> EthSecret {
        let mut bytes = [0u8; 32];
        bytes[31] = 7;
        EthSecret::from_bytes(&bytes).unwrap()
    }

    #[test]
    fn pipe_handle_is_random_and_not_endpoint_derived() {
        let a = new_pipe_handle();
        let b = new_pipe_handle();
        assert_ne!(a, b);
        assert_eq!(a.len(), 64);
        assert!(a.bytes().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn offer_is_keyed_by_main_wallet_and_port() {
        let key = aes::generate_key();
        let main = "0x2222222222222222222222222222222222222222";
        let initiator = "0x1111111111111111111111111111111111111111";
        let cmd = encode_offer_command_for_port(
            initiator,
            main,
            main,
            initiator,
            "",
            8400,
            &new_pipe_handle(),
            &key,
            1,
        )
        .unwrap();
        let offer = parse_offer_plain(&cmd).unwrap();
        assert_eq!(offer.main_wallet, main);
        assert_eq!(offer.port, 8400);
        assert_eq!(offer.from, initiator);
    }

    #[test]
    fn accept_echoes_key_reject_and_frame_do_not() {
        let key = aes::generate_key();
        let cmd = encode_accept_command(
            "0x1111111111111111111111111111111111111111",
            "0x1111111111111111111111111111111111111111",
            "",
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            &key,
            1,
        )
        .unwrap();
        assert!(cmd.contains("duplex_accept"));
        assert!(cmd.contains("Securitykey"));
        assert!(!cmd.contains("p2p_stream"));
        let reject = encode_reject_command(
            "0x1111111111111111111111111111111111111111",
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            2,
        )
        .unwrap();
        assert!(reject.contains("duplex_reject"));
        assert!(!reject.contains("Securitykey"));
        let frame = encode_frame_json(
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "YmFzZQ==",
        )
        .unwrap();
        assert!(frame.contains("duplex_frame"));
        assert!(!frame.contains("Securitykey"));
        assert!(!frame.contains("duplex_relay"));
    }

    #[test]
    fn offer_contains_key_and_wrap_is_user_pgp() {
        let eth = test_eth();
        let user = generate_test_cert();
        let user_pub = public_cert_armored(&user).unwrap();
        let key = aes::generate_key();
        let cmd = encode_offer_command(
            eth.address(),
            "0x2222222222222222222222222222222222222222",
            eth.address(),
            &user_pub,
            "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
            &key,
            9,
        )
        .unwrap();
        assert!(cmd.contains("Securitykey"));
        let armor = wrap_offer_for_user_pgp(&cmd, &user_pub, &eth).unwrap();
        let b64 = decrypt_utf8(&armor, &user).unwrap();
        let raw = Engine::decode(&base64::engine::general_purpose::STANDARD, b64.trim()).unwrap();
        let wrapper: Value = serde_json::from_slice(&raw).unwrap();
        let message = wrapper["message"].as_str().unwrap();
        let offer = parse_offer_plain(message).unwrap();
        assert_eq!(offer.key, key);
    }

    #[test]
    fn inbound_plain_parses_signed_offer_and_accept() {
        let eth = test_eth();
        let key = aes::generate_key();
        let cmd = encode_offer_command(
            eth.address(),
            "0x2222222222222222222222222222222222222222",
            eth.address(),
            "",
            "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
            &key,
            3,
        )
        .unwrap();
        let sign = eth.personal_sign(cmd.as_bytes()).unwrap();
        let wrapper = serde_json::json!({ "message": cmd, "signMessage": sign }).to_string();
        let offer = parse_offer_from_inbound_plain(&wrapper).unwrap();
        assert_eq!(offer.key, key);
        let accept = encode_accept_command(
            eth.address(),
            eth.address(),
            "",
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
            &key,
            4,
        )
        .unwrap();
        let sign_a = eth.personal_sign(accept.as_bytes()).unwrap();
        let wrap_a = serde_json::json!({ "message": accept, "signMessage": sign_a }).to_string();
        let got = parse_accept(&wrap_a).expect("accept");
        assert_eq!(
            got.session_id,
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
        );
        assert_eq!(got.key, key);
        let reject = encode_reject_command(eth.address(), &got.session_id, 5).unwrap();
        let sign_r = eth.personal_sign(reject.as_bytes()).unwrap();
        let wrap_r = serde_json::json!({ "message": reject, "signMessage": sign_r }).to_string();
        assert_eq!(
            parse_reject(&wrap_r).as_deref(),
            Some(got.session_id.as_str())
        );
    }

    #[test]
    fn seal_frame_is_aes_blob_not_pgp() {
        let key = aes::generate_key();
        let blob = seal_frame(&key, "aa", b"L0D1xxxx").unwrap();
        assert!(looks_like_aes_blob(&blob));
        assert!(!blob.contains("BEGIN PGP"));
        let plain = String::from_utf8(aes::open(&key, &blob).unwrap()).unwrap();
        let (sid, payload) = parse_duplex_frame_json(&plain).unwrap();
        assert_eq!(sid, "aa");
        assert!(!payload.contains("Securitykey"));
    }

    #[test]
    fn parse_l0_pipe_end_requires_opaque_handle() {
        let end = parse_l0_pipe_end(
            r#"{"type":"l0_pipe_end","pipe_handle":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","reason":"inbound_close"}"#,
        )
        .unwrap();
        assert_eq!(end.reason, "inbound_close");
        assert_eq!(
            end.pipe_handle,
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        );
        assert!(parse_l0_pipe_end(
            r#"{"type":"l0_pipe_end","pipe_handle":"wrong","reason":"inbound_close"}"#
        )
        .is_none());
        assert!(parse_l0_pipe_end(
            r#"{"type":"l0_pipe_end","sessionId":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","reason":"inbound_close"}"#
        ).is_none());
        assert!(parse_l0_pipe_end(r#"{"type":"l0_occupied"}"#).is_none());
    }
}
